### ISSUE TITLE
how to use or config with typescript

### ISSUE THREAD

**Issue by poerlang** [UziTech/eslint-linter-browserify#213]
when verify this code:
```
const doAction = (name:string)=>{
  console.log(name + ' just do it');
}
```
there is a error:
`Parsing error: Unexpected token :`

https://stackblitz.com/edit/vitejs-vite-ccog6i?file=src/App.vue

**Comment by poerlang** [comment]
https://codesandbox.io/s/wonderful-lumiere-bcs19g?file=/src/App.vue

**Comment by UziTech** [comment]
I haven't tried using this with typescript but it should be similar to the way you configure eslint with [`typescript-eslint`](https://github.com/typescript-eslint/typescript-eslint)

**Comment by as1605** [comment]
Hi, can you let me know the way to configure this with an example? 

I'm working on a similar project
