### ISSUE TITLE
ReferenceError: eslint is not defined

### ISSUE THREAD

**Issue by EskelCz** [UziTech/eslint-linter-browserify#234]
Thanks for the example but where is the browser supposed to get the lower case `eslint`? 
`new eslint.Linter()` in your code.

**Comment by UziTech** [comment]
It is `eslint` looks like you are missing the L. 

`eslint` is added as a global variable.

**Comment by EskelCz** [comment]
@UziTech Sorry that was a typo, fixed it.
Still, global variable in a browser? I don't get it, like window.eslint? How will would it get there?

**Comment by EskelCz** [comment]
Oh I missed the <script src="./bundle.js" type="module"></script> :) How silly, sorry
