### ISSUE TITLE
I can't reproduce the example: Linter is not exported by node_modules/eslint-linter-browserify/linter.js

### ISSUE THREAD

**Issue by morales-alex** [UziTech/eslint-linter-browserify#251]
Hello, I think there could be an error in the example. I can't replicate it. I have the following error:
![image](https://user-images.githubusercontent.com/95450177/210743000-942f3f70-d9b1-4bcb-8ea9-ee9efcc11887.png)
It seems that LInter() is not exported.
I hope I can be of help, thanks in advance.

**Comment by UziTech** [comment]
Yes the releases happen on eslint schedule to follow their version number. I just merged the new rollup files but they are not released yet try the example at https://github.com/UziTech/eslint-linter-browserify/tree/v8.31.0 when the next version of eslint is released `import { Linter } from "eslint-linter-browserify";` should work.
