### ISSUE TITLE
Usage in browser code editor

### ISSUE THREAD

**Issue by abose** [UziTech/eslint-linter-browserify#254]
Hi ,
 
 I was looking for an in-browser version of eslint for use in https://phcode.dev, part of [brackets.io](https://brackets.io) and just found this repo. 
 1. Can I use this to enable eslint APIs in the browser?
 2. Is it stable for use in a web worker/browser environment?
 3. Does it support typescript lint/ any limitations.

Best,
Arun.

**Comment by UziTech** [comment]
Ya that is what this is meant for. You can see the example that uses code mirror [here](https://github.com/UziTech/eslint-linter-browserify/tree/master/example).

**Comment by UziTech** [comment]
This is just eslint with everything stripped out that is node specific. If typescript plugins don't use node specific api it can be used as a plugin. I'm guessing some work will be needed to make that happen.

**Comment by abose** [comment]
Awesome :D Thanks for the work!

**Comment by abose** [comment]
Hello again, Is there any way to get a js min distribution via npm or any release or dist dir in this github repo itself? What is the recommend way to do this.

**Comment by UziTech** [comment]
There will be a min file in the next release. The readme has instructions for accessing it. Otherwise you can build the min file from the repo.

**Comment by abose** [comment]
Thanks that would unblock the development.
Waiting for the next release for the recommended dist assets to merge through our build system.

**Comment by UziTech** [comment]
The latest release should be out with the new build files
