### ISSUE TITLE
JSX and React support

### ISSUE THREAD

**Issue by ramisich** [UziTech/eslint-linter-browserify#260]
Hi and thanks for the great work. is it possible to lint React js file and jsx files?
Imagine this code:
```
import Test from "./App.js";
import App from "./nice/Test.js";
import React from "react";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
const rootElement = document.getElementById("root");
const root = createRoot(rootElement);

root.render(
  <StrictMode>
    <Tes />
    <App />    
  </StrictMode>
);
```
It should for example say unused import at `import Test from "./App.js";` and also Tes not defined here `<Tes />`

Thanks!

**Comment by UziTech** [comment]
I have not tried adding plugins but if they don't require node apis they should work.

**Comment by ramisich** [comment]
Unfortunately they do and at this moment a lot of js code is based on React and jsx. Therefore its safe to assume that eslint-linter-browserify is only for linting simple javascript code.

Thanks anyways

**Comment by UziTech** [comment]
Ya this is meant to be run in the browser. It seems you may need an API for sending code to be linted on a server.
