### ISSUE TITLE
Import in vite project

### ISSUE THREAD

**Issue by LaKing** [UziTech/eslint-linter-browserify#276]
Hello, ...

I'm using Vite, and the import statement crashes at the `save(namespace)` function, as `process.env` is undefined.

So namespaces exists, but process.env doesent. 

Maybe we could add an additional check?

**Comment by UziTech** [comment]
Sure PRs are always welcome 😁👍

**Comment by moh3nmx** [comment]
> Same here using Codemirror 6, Vue 3 and nuxt 3

Same issue
