### ISSUE TITLE
Enabling TypeScript Support on Development

### ISSUE THREAD

**Issue by as1605** [UziTech/eslint-linter-browserify#324]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

The current bundle for the package does not utilise the `index.d.ts` type declarations. I have included them and updated them in the `package.json` accordingly so they can be identified by the TypeScript linter for the development environment.

Please merge these changes to allow the project to be integrated in TypeScript codebases (for example ReactJS with TypeScript setups)

Understand that this is different than supporting TypeScript for parsing, for which we'll have to patch [@typescript-eslint/parser](https://www.npmjs.com/package/@typescript-eslint/parser) accordingly

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `eslint-linter-browserify@8.43.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/eslint-linter-browserify/index.d.ts b/node_modules/eslint-linter-browserify/index.d.ts
new file mode 100644
index 0000000..67b62b4
--- /dev/null
+++ b/node_modules/eslint-linter-browserify/index.d.ts
@@ -0,0 +1 @@
+export { Linter } from 'eslint'
\ No newline at end of file
diff --git a/node_modules/eslint-linter-browserify/index.js b/node_modules/eslint-linter-browserify/index.js
new file mode 100644
index 0000000..8c1e2fc
--- /dev/null
+++ b/node_modules/eslint-linter-browserify/index.js
@@ -0,0 +1,9 @@
+if (typeof process === "undefined") {
+	(window || globalThis).process = require("process/browser");
+}
+
+function getLinter() {
+	return require("./node_modules/eslint/lib/linter/linter").Linter;
+}
+
+module.exports.Linter = getLinter();
\ No newline at end of file
diff --git a/node_modules/eslint-linter-browserify/package.json b/node_modules/eslint-linter-browserify/package.json
index 2ace047..9dfd2e7 100644
--- a/node_modules/eslint-linter-browserify/package.json
+++ b/node_modules/eslint-linter-browserify/package.json
@@ -14,7 +14,10 @@
   "types": "index.d.ts",
   "exports": {
     ".": {
-      "import": "./linter.mjs",
+      "import": {
+        "types": "./index.d.ts",
+        "default": "./linter.mjs"
+      },
       "default": "./linter.cjs"
     },
     "./linter.js": "./linter.js",
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by UziTech** [comment]
If you create a PR we can get this merged 👍
