### ISSUE TITLE
Extends and fix configurations

### ISSUE THREAD

**Issue by anthonyjclark** [UziTech/eslint-linter-browserify#365]
Hello,

I'd like to use the `extends` configuration. You can see its use on [this page](https://eslint.org/docs/latest/integrate/nodejs-api#linter). Something like this:

```js
const config = {
	// eslint configuration
	parserOptions: {
		ecmaVersion: 2019,
		sourceType: "module",
	},
	env: {
		browser: true,
		node: true,
	},
	rules: {
		semi: ["error", "never"],
	},
	extends: ["eslint:recommended"],
};
```

I'd also like to use eslints fixing/autoformatting features, but I am not sure how they interact with CodeMirror. I'd be happy to submit a PR if you could give some guidance on either of these features.

**Comment by UziTech** [comment]
I think extend should already work but this package wouldn't have anything to do with fixing the linting errors. You would have to do that with codemirror somehow.

**Comment by anthonyjclark** [comment]
Do you have an idea how I could use a third party set of rules with `extends`? For example: https://www.npmjs.com/package/eslint-config-mdcs

Eslint does have a [fix](https://eslint.org/docs/latest/use/command-line-interface#fix-problems) feature, but like you said I probably need to handle that outside of what the linter is doing.

**Comment by UziTech** [comment]
I do not know. If you figure it out we could add some docs to the readme
