### ISSUE TITLE
linter.js report window is not defined  in service worker

### ISSUE THREAD

**Issue by rhlin** [UziTech/eslint-linter-browserify#384]
`eslint-linter-browserify` package version: 8.56.0

I try to use `linter.js` in service worker (to mark eslint error in monaco editor), it broked with follow message
```
Uncaught ReferenceError: window is not defined
at linter.js:131409:6
at linter.js:4:80
at linter.js:5:3
……
```
Code here [index.js  Line 2](https://github.com/UziTech/eslint-linter-browserify/blob/1d563a9bfe930e6bc5485b9bb85a71bb5bd8d499/index.js#L2C2-L2C24) would be better with `global.process = require("process/browser")` instead of `(window || globalThis).process = require("process/browser");`

I repalced  `(window || globalThis)` with `global` and it works in service worker.

Could you fix that in next release ?

**Comment by UziTech** [comment]
Can you create a PR with this fix?

**Comment by UziTech** [comment]
I think we still need window for working outside of service worker. Does it work to just add global with something like `(global || window || globalThis)`?
