### ISSUE TITLE
Allow global return statements

### ISSUE THREAD

**Issue by henriklippke** [UziTech/eslint-linter-browserify#416]
Could you help me to allow global return statements?
Because I thought if I set the sourceType to commonJs then I am able to use the ecmaFeatures "globalReturn". Or do I have to set the platform to node?  
 
```
languageOptions: {
  globals: Object.fromEntries(GloablPackages.map(item => [item, "readonly"])),
  parserOptions: {
    sourceType: "commonjs",
    ecmaVersion: 2022,
    ecmaFeatures: {
      impliedStrict: true,
      globalReturn: true
    }
  },
},
```

**Comment by UziTech** [comment]
This seems like a question for [eslint](https://github.com/eslint/eslint). This project just uses rollup to allow eslint to be used in a script tag.
